/**
 * AutoGen Adapter Generator (Python only)
 *
 * Bridges AutoGen's GroupChat / Agent to WWA IACP.
 * AutoGen is Python-only — no TypeScript adapter.
 */

import { Generator, GeneratorOptions, GeneratorResult, SupportedLanguage } from "./base";
import { detect } from "../detectors/detect";

export class AutoGenGenerator extends Generator {
  readonly framework = "autogen";

  get supportedLanguages(): SupportedLanguage[] {
    return ["python"]; // Python only
  }

  async detect(projectPath: string): Promise<boolean> {
    const info = detect(projectPath);
    return info.framework === "autogen";
  }

  async generate(
    _projectPath: string,
    _language: SupportedLanguage,
    options: GeneratorOptions,
  ): Promise<GeneratorResult[]> {
    const results: GeneratorResult[] = [];
    const caps = options.capabilities;
    const wantsIacpOrHandoff = !caps || caps.includes("iacp") || caps.includes("handoff");
    const wantsManifest = !caps || caps.includes("manifest");
    const wantsIdentity = !caps || caps.includes("identity");

    if (wantsIacpOrHandoff) {
      results.push({ file: "wwa_agent.py", content: this.generatePythonAdapter(options) });
    }

    if (wantsManifest) {
      results.push({ file: "manifest.yaml", content: this.generateManifest(options, wantsIdentity) });
    }

    return results;
  }

  private generatePythonAdapter(options: GeneratorOptions): string {
    const regBlock = options.registryUrl
      ? `
REGISTRY_URL = "${options.registryUrl}"
AGENT_ID = "${options.agentId}"
ENDPOINT = "${options.endpoint}"

import atexit, urllib.request, json as _json
def _register():
    try:
        req = urllib.request.Request(f"{REGISTRY_URL}/v1/agents/register",
            data=_json.dumps({"manifest_version":"1.0.0","agent_id":AGENT_ID,"capabilities":[{"action":"autogen_chat","target":"iacp"}],"tools":["autogen","iacp"],"endpoint":{"address":ENDPOINT,"protocol":"acp"},"status":{"state":"healthy","load":0,"current_tasks":0,"max_tasks":10}}).encode(),
            headers={"Content-Type":"application/json"})
        urllib.request.urlopen(req)
        print(f"[wwa] Registered '{AGENT_ID}'")
    except Exception as e: print(f"[wwa] Registration skipped: {e}")
def _deregister():
    try: urllib.request.urlopen(urllib.request.Request(f"{REGISTRY_URL}/v1/agents/{AGENT_ID}", method="DELETE"))
    except: pass
_register(); atexit.register(_deregister)`
      : `# Registration disabled.`;

    return `"""
WWA AutoGen Adapter — ${options.agentId}
Generated by wwa-cli for AutoGen (Python only).

Extends AutoGen's ConversableAgent to speak IACP.
Registers group chat agents as WWA capabilities.
"""

import os, json, uuid
from datetime import datetime, timezone

HANDOFF_ENDPOINT = "${options.endpoint}"
AGENT_ID = "${options.agentId}"
${regBlock}

try:
    from autogen import ConversableAgent, GroupChat, GroupChatManager

    class WWAConversableAgent(ConversableAgent):
        """AutoGen agent that can receive IACP handoffs."""

        def __init__(self, name, wwa_capabilities=None, **kwargs):
            super().__init__(name, **kwargs)
            self.wwa_capabilities = wwa_capabilities or []
            print(f"[wwa] Agent '{name}' ready with {len(self.wwa_capabilities)} capabilities")

        def handle_iacp_message(self, envelope: dict) -> dict:
            intent = envelope.get("intent", "handoff")
            if intent == "handoff" and envelope.get("type") == "request":
                task = envelope.get("payload", {})
                msg = {
                    "content": task.get("task_description", ""),
                    "role": "user",
                    "context": task.get("context", {}),
                }
                reply = self.generate_reply(messages=[msg])
                return {
                    "type": "response", "intent": "handoff", "status": "completed",
                    "payload": {"result": reply},
                    "message_id": str(uuid.uuid4()),
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                }
            return {
                "type": "error", "intent": intent, "status": "unknown_intent",
                "payload": {"error": f"Intent '{intent}' not supported"},
                "message_id": str(uuid.uuid4()),
                "timestamp": datetime.now(timezone.utc).isoformat(),
            }

    print("[wwa] WWAConversableAgent ready — extend this class for your agents.")

except ImportError:
    print("[wwa] AutoGen not installed: pip install pyautogen")
    WWAConversableAgent = None

# ── IACP HTTP Server (FastAPI) ──────────────────────────

try:
    from fastapi import FastAPI
    from fastapi.middleware.cors import CORSMiddleware

    app = FastAPI(title=f"WWA AutoGen Adapter: {AGENT_ID}")
    app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

    _agent_registry: dict = {}

    @app.post("/iacp/message")
    async def iacp_message(envelope: dict):
        return {"type": "response", "intent": "handoff", "status": "routed",
                "payload": {"message": "Message routed to AutoGen group chat"},
                "message_id": str(uuid.uuid4()),
                "timestamp": datetime.now(timezone.utc).isoformat()}

    @app.post("/v1/agents/register")
    async def register_agent(agent_config: dict):
        agent_name = agent_config.get("agent_id", AGENT_ID)
        _agent_registry[agent_name] = agent_config
        return {"status": "registered", "agent_id": agent_name}

    @app.get("/agents")
    async def list_agents():
        return {"agents": list(_agent_registry.keys()), "count": len(_agent_registry)}

    @app.get("/health")
    async def health():
        return {"status": "healthy", "agent_id": AGENT_ID, "framework": "autogen"}

    print(f"[wwa] AutoGen IACP listener ready at http://{HANDOFF_ENDPOINT}/iacp/message")

except ImportError:
    print("[wwa] FastAPI not installed: pip install fastapi uvicorn")
`;
  }

  private generateManifest(options: GeneratorOptions, includeIdentity: boolean = true): string {
    const identityBlock = includeIdentity
      ? `\nidentity:\n  agent_id: "${options.agentId}"\n  protocol: identity/v1.1.0`
      : "";
    const reg = options.registryUrl
      ? `registry:\n  url: "${options.registryUrl}"\n  auto_register: true\n  auto_deregister: true`
      : `registry:\n  auto_register: false`;

    return `# WWA Capability Manifest — ${options.agentId}
manifest_version: "1.0.0"
agent_id: "${options.agentId}"
framework: autogen
endpoint: "${options.endpoint}"

capabilities:
  - action: autogen_chat
    target: iacp
    description: "AutoGen group chat via IACP"
  - action: autogen_register
    target: iacp
    description: "Register AutoGen agents in group chat"

tools:
  - autogen
  - iacp
${identityBlock}
iacp:
  endpoint: "/iacp/message"
  intents:
    - handoff
    - health
    - register

${reg}
`;
  }
}
