/**
 * CrewAI Adapter Generator (Python only)
 *
 * Bridges CrewAI's Crew / Agent to WWA IACP and Delegation Framework.
 * CrewAI is Python-only — no TypeScript adapter.
 */

import { Generator, GeneratorOptions, GeneratorResult, SupportedLanguage } from "./base";
import { detect } from "../detectors/detect";

export class CrewAIGenerator extends Generator {
  readonly framework = "crewai";

  get supportedLanguages(): SupportedLanguage[] {
    return ["python"]; // Python only
  }

  async detect(projectPath: string): Promise<boolean> {
    const info = detect(projectPath);
    return info.framework === "crewai";
  }

  async generate(
    _projectPath: string,
    _language: SupportedLanguage,
    options: GeneratorOptions,
  ): Promise<GeneratorResult[]> {
    const results: GeneratorResult[] = [];
    const caps = options.capabilities;
    const wantsIacpOrHandoff = !caps || caps.includes("iacp") || caps.includes("handoff");
    const wantsManifest = !caps || caps.includes("manifest");
    const wantsIdentity = !caps || caps.includes("identity");

    if (wantsIacpOrHandoff) {
      results.push({ file: "wwa_crew_adapter.py", content: this.generatePythonAdapter(options) });
    }

    if (wantsManifest) {
      results.push({ file: "manifest.yaml", content: this.generateManifest(options, wantsIdentity) });
    }

    return results;
  }

  private generatePythonAdapter(options: GeneratorOptions): string {
    const regBlock = options.registryUrl
      ? `
REGISTRY_URL = "${options.registryUrl}"
AGENT_ID = "${options.agentId}"
ENDPOINT = "${options.endpoint}"

import atexit, urllib.request, json as _json
def _register():
    try:
        req = urllib.request.Request(f"{REGISTRY_URL}/v1/agents/register",
            data=_json.dumps({"manifest_version":"1.0.0","agent_id":AGENT_ID,"capabilities":[{"action":"crewai_kickoff","target":"iacp"}],"tools":["crewai","iacp"],"endpoint":{"address":ENDPOINT,"protocol":"acp"},"status":{"state":"healthy","load":0,"current_tasks":0,"max_tasks":10}}).encode(),
            headers={"Content-Type":"application/json"})
        urllib.request.urlopen(req)
        print(f"[wwa] Registered '{AGENT_ID}'")
    except Exception as e: print(f"[wwa] Registration skipped: {e}")
def _deregister():
    try: urllib.request.urlopen(urllib.request.Request(f"{REGISTRY_URL}/v1/agents/{AGENT_ID}", method="DELETE"))
    except: pass
_register(); atexit.register(_deregister)`
      : `# Registration disabled.`;

    return `"""
WWA Crew Adapter — ${options.agentId}
Generated by wwa-cli for CrewAI (Python only).

Wraps CrewAI's Crew.kickoff() in an IACP listener.
Maps role-based agents to WWA capability manifests.
"""
import os, json, uuid
from datetime import datetime, timezone

HANDOFF_ENDPOINT = "${options.endpoint}"
AGENT_ID = "${options.agentId}"
${regBlock}

# Import your CrewAI crew:
# from your_crew import MyCrew
# crew = MyCrew()

try:
    from crewai import Crew, Agent, Task, Process

    # Placeholder — replace with your actual crew definition
    def create_wwa_crew(task_description: str, context: dict = None):
        """Create a CrewAI crew for the given IACP task."""
        researcher = Agent(
            role="Researcher",
            goal="Research the given topic thoroughly",
            backstory="Expert researcher with deep domain knowledge",
            verbose=True,
        )
        writer = Agent(
            role="Writer",
            goal="Write clear, concise reports",
            backstory="Skilled technical writer",
            verbose=True,
        )

        task = Task(
            description=task_description,
            expected_output="A comprehensive report",
            agent=researcher,
        )

        crew = Crew(
            agents=[researcher, writer],
            tasks=[task],
            process=Process.sequential,
            verbose=True,
        )

        return crew

    print("[wwa] CrewAI adapter ready.")

except ImportError:
    print("[wwa] CrewAI not installed: pip install crewai")
    create_wwa_crew = None

# ── Agent Role → Capability Mapping ─────────────────────

def role_to_capability(role: str) -> dict:
    """Map CrewAI agent roles to WWA capability declarations."""
    role_map = {
        "researcher": {"action": "research", "target": "knowledge", "success_rate": 0.95},
        "writer": {"action": "write", "target": "documentation", "success_rate": 0.92},
        "reviewer": {"action": "review", "target": "quality", "success_rate": 0.90},
        "coder": {"action": "code", "target": "software", "success_rate": 0.88},
        "analyst": {"action": "analyze", "target": "data", "success_rate": 0.93},
    }
    return role_map.get(role.lower(), {"action": "generic", "target": "unknown", "success_rate": 0.85})

# ── IACP Message Handler ────────────────────────────────

def handle_iacp_message(envelope: dict) -> dict:
    """Process IACP message via CrewAI."""
    intent = envelope.get("intent", "handoff")

    if intent == "handoff" and envelope.get("type") == "request":
        task = envelope.get("payload", {})
        task_description = task.get("task_description", "")
        context = task.get("context", {})

        if create_wwa_crew:
            try:
                crew = create_wwa_crew(task_description, context)
                result = crew.kickoff()
                return {
                    "type": "response",
                    "intent": "handoff",
                    "status": "completed",
                    "payload": {"result": str(result)},
                    "message_id": str(uuid.uuid4()),
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                }
            except Exception as e:
                return {
                    "type": "error", "intent": "handoff", "status": "crew_failed",
                    "payload": {"error": str(e)},
                    "message_id": str(uuid.uuid4()),
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                }
        else:
            return {
                "type": "response", "intent": "handoff", "status": "unavailable",
                "payload": {"result": "CrewAI not configured. Edit wwa_crew_adapter.py"},
                "message_id": str(uuid.uuid4()),
                "timestamp": datetime.now(timezone.utc).isoformat(),
            }

    if intent == "delegate":
        # WWA Delegation Framework — map task to the right agent role
        task = envelope.get("payload", {})
        role = task.get("role", "researcher")
        capability = role_to_capability(role)
        return {
            "type": "response", "intent": "delegate", "status": "accepted",
            "payload": {"assigned_role": role, "capability": capability},
            "message_id": str(uuid.uuid4()),
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

    return {
        "type": "error", "intent": intent, "status": "unknown_intent",
        "payload": {"error": f"Intent '{intent}' not supported"},
        "message_id": str(uuid.uuid4()),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }

# ── FastAPI IACP Server ──────────────────────────────────

try:
    from fastapi import FastAPI
    from fastapi.middleware.cors import CORSMiddleware

    app = FastAPI(title=f"WWA CrewAI Adapter: {AGENT_ID}")
    app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

    @app.post("/iacp/message")
    async def iacp_message(envelope: dict):
        return handle_iacp_message(envelope)

    @app.get("/health")
    async def health():
        return {"status": "healthy", "agent_id": AGENT_ID, "framework": "crewai"}

    @app.get("/agents/roles")
    async def list_roles():
        """Expose CrewAI agent roles as WWA capabilities."""
        return {
            "agent_id": AGENT_ID,
            "roles": [
                {"role": "researcher", "capability": role_to_capability("researcher")},
                {"role": "writer", "capability": role_to_capability("writer")},
                {"role": "reviewer", "capability": role_to_capability("reviewer")},
                {"role": "coder", "capability": role_to_capability("coder")},
                {"role": "analyst", "capability": role_to_capability("analyst")},
            ]
        }

    print(f"[wwa] CrewAI IACP listener ready at http://{HANDOFF_ENDPOINT}/iacp/message")

except ImportError:
    print("[wwa] FastAPI not installed: pip install fastapi uvicorn")
`;
  }

  private generateManifest(options: GeneratorOptions, includeIdentity: boolean = true): string {
    const identityBlock = includeIdentity
      ? `\nidentity:\n  agent_id: "${options.agentId}"\n  protocol: identity/v1.1.0`
      : "";
    const reg = options.registryUrl
      ? `registry:\n  url: "${options.registryUrl}"\n  auto_register: true\n  auto_deregister: true`
      : `registry:\n  auto_register: false`;

    return `# WWA Capability Manifest — ${options.agentId}
manifest_version: "1.0.0"
agent_id: "${options.agentId}"
framework: crewai
endpoint: "${options.endpoint}"

capabilities:
  - action: crewai_kickoff
    target: iacp
    description: "Kickoff CrewAI crew via IACP"
  - action: delegate_task
    target: role_assignment
    description: "Delegate tasks to CrewAI agent roles"

roles:
  - researcher
  - writer
  - reviewer
  - coder
  - analyst

tools:
  - crewai
  - iacp
${identityBlock}
iacp:
  endpoint: "/iacp/message"
  intents:
    - handoff
    - delegate
    - health

delegation:
  supported: true
  role_based: true

${reg}
`;
  }
}
