/**
 * LangGraph Adapter Generator (Python + TypeScript)
 *
 * Generates WWA adapter code for LangGraph's StateGraph / CompiledGraph.
 * Both Python (.py) and TypeScript (.ts) adapters are supported.
 */

import * as path from "path";
import * as fs from "fs";
import * as Handlebars from "handlebars";
import { Generator, GeneratorOptions, GeneratorResult, SupportedLanguage } from "./base";
import { detect } from "../detectors/detect";

export class LangGraphGenerator extends Generator {
  readonly framework = "langgraph";

  get supportedLanguages(): SupportedLanguage[] {
    return ["python", "typescript"];
  }

  async detect(projectPath: string): Promise<boolean> {
    const info = detect(projectPath);
    return info.framework === "langgraph";
  }

  async generate(
    projectPath: string,
    language: SupportedLanguage,
    options: GeneratorOptions,
  ): Promise<GeneratorResult[]> {
    const results: GeneratorResult[] = [];
    const caps = options.capabilities;
    const wantsIacpOrHandoff = !caps || caps.includes("iacp") || caps.includes("handoff");
    const wantsManifest = !caps || caps.includes("manifest");
    const wantsIdentity = !caps || caps.includes("identity");

    // Generate IACP/Handoff adapter
    if (wantsIacpOrHandoff) {
      const ext = language === "python" ? "py" : "ts";
      const templateFile = language === "python"
        ? "langgraph_handoff.py.j2"
        : "langgraph_handoff.ts.j2";
      const templatePath = path.join(this.templatesPath(language), templateFile);

      if (!fs.existsSync(templatePath)) {
        const content = language === "python"
          ? this.generatePythonAdapter(options)
          : this.generateTypeScriptAdapter(options);
        results.push({ file: `wwa_handoff.${ext}`, content });
      } else {
        const template = Handlebars.compile(fs.readFileSync(templatePath, "utf-8"));
        const content = template(options);
        results.push({ file: `wwa_handoff.${ext}`, content });
      }
    }

    // Generate Capability Manifest
    if (wantsManifest) {
      results.push({
        file: "manifest.yaml",
        content: this.generateManifest(options, wantsIdentity),
      });
    }

    return results;
  }

  private generatePythonAdapter(options: GeneratorOptions): string {
    const regBlock = options.registryUrl
      ? `
# ── WWA Registry Auto-Registration ─────────────────────
import atexit
import urllib.request
import json as _json

REGISTRY_URL = "${options.registryUrl}"
AGENT_ID = "${options.agentId}"
ENDPOINT = "${options.endpoint}"

def _register():
    try:
        req = urllib.request.Request(
            f"{REGISTRY_URL}/v1/agents/register",
            data=_json.dumps({
                "manifest_version": "1.0.0",
                "agent_id": AGENT_ID,
                "capabilities": [{"action": "langgraph_invoke", "target": "iacp", "success_rate": 0.99}],
                "tools": ["langgraph", "iacp"],
                "endpoint": {"address": ENDPOINT, "protocol": "acp"},
                "status": {"state": "healthy", "load": 0.0, "current_tasks": 0, "max_tasks": 10}
            }).encode(),
            headers={"Content-Type": "application/json"}
        )
        urllib.request.urlopen(req)
        print(f"[wwa] Registered agent '{AGENT_ID}' at {REGISTRY_URL}")
    except Exception as e:
        print(f"[wwa] Registration skipped (registry unreachable): {e}")

def _deregister():
    try:
        req = urllib.request.Request(
            f"{REGISTRY_URL}/v1/agents/{AGENT_ID}",
            method="DELETE"
        )
        urllib.request.urlopen(req)
        print(f"[wwa] Deregistered agent '{AGENT_ID}'")
    except Exception:
        pass

_register()
atexit.register(_deregister)
# ──────────────────────────────────────────────────────
`
      : `# Registration disabled. Set WWA_REGISTRY_URL to enable.`;

    return `"""
WWA Handoff adapter — ${options.projectName || options.agentId}

Generated by wwa-cli for LangGraph.
Do not edit manually — regenerate with 'wwa init'.
"""
import os
import json
import uuid
from datetime import datetime, timezone
from typing import Any, Optional

# ── Override registry URL at runtime ─────────────────
REGISTRY_URL = os.environ.get("WWA_REGISTRY_URL", "${options.registryUrl || ""}")

# Import your compiled LangGraph
# Update this import to match your project's graph location:
# from your_module import graph
try:
    from ${options.graphImportPath || ".graph import graph"}
except ImportError:
    graph = None
    print("[wwa] Warning: LangGraph not found. Install with: pip install langgraph")

HANDOFF_ENDPOINT = "${options.endpoint}"
AGENT_ID = "${options.agentId}"

${regBlock}

# ── IACP Message Handling ────────────────────────────

def handle_iacp_message(envelope: dict) -> dict:
    """Process an IACP message and route to the LangGraph."""
    if graph is None:
        return _error("langgraph_not_available", "LangGraph is not imported")

    message_type = envelope.get("type", "request")
    intent = envelope.get("intent", "handoff")

    if intent == "handoff" and message_type == "request":
        task = envelope.get("payload", {})

        try:
            result = graph.invoke({
                "input": task.get("task_description", ""),
                "context": task.get("context", {}),
                "tools": task.get("tools_required", []),
            })

            return {
                "type": "response",
                "intent": "handoff",
                "status": "completed",
                "payload": {"result": result},
                "message_id": str(uuid.uuid4()),
                "timestamp": datetime.now(timezone.utc).isoformat(),
            }
        except Exception as e:
            return _error("invoke_failed", str(e))

    if intent == "health":
        return {
            "type": "heartbeat",
            "intent": "health",
            "status": "healthy",
            "payload": {"agent_id": AGENT_ID, "endpoint": HANDOFF_ENDPOINT},
            "message_id": str(uuid.uuid4()),
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

    return _error("unknown_intent", f"Intent '{intent}' not supported")

def _error(code: str, detail: str) -> dict:
    return {
        "type": "error",
        "intent": "unknown",
        "status": code,
        "payload": {"error": detail},
        "message_id": str(uuid.uuid4()),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }

# ── HTTP Server (FastAPI) ────────────────────────────

# To start the IACP listener:
#   pip install fastapi uvicorn
#   uvicorn wwa_handoff:app --host 0.0.0.0 --port 8787

try:
    from fastapi import FastAPI
    from fastapi.middleware.cors import CORSMiddleware

    app = FastAPI(title=f"WWA Adapter: {AGENT_ID}")
    app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

    @app.post("/iacp/message")
    async def iacp_message(envelope: dict):
        return handle_iacp_message(envelope)

    @app.get("/health")
    async def health():
        return {"status": "healthy", "agent_id": AGENT_ID}

    print(f"[wwa] IACP listener ready at http://{HANDOFF_ENDPOINT}/iacp/message")

except ImportError:
    print("[wwa] FastAPI not installed. IACP HTTP server not available.")
    print("       Install with: pip install fastapi uvicorn")
`;
  }

  private generateTypeScriptAdapter(options: GeneratorOptions): string {
    const regBlock = options.registryUrl
      ? `
// ── WWA Registry Auto-Registration ────────────────────
const REGISTRY_URL = "${options.registryUrl}";
const AGENT_ID = "${options.agentId}";
const ENDPOINT = "${options.endpoint}";

async function register() {
  try {
    await fetch(\`\${REGISTRY_URL}/v1/agents/register\`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        manifest_version: "1.0.0",
        agent_id: AGENT_ID,
        capabilities: [{ action: "langgraph_invoke", target: "iacp", success_rate: 0.99 }],
        tools: ["langgraph", "iacp"],
        endpoint: { address: ENDPOINT, protocol: "acp" },
        status: { state: "healthy", load: 0.0, current_tasks: 0, max_tasks: 10 },
      }),
    });
    console.log(\`[wwa] Registered agent '\${AGENT_ID}' at \${REGISTRY_URL}\`);
  } catch (e) {
    console.log(\`[wwa] Registration skipped (registry unreachable): \${e}\`);
  }
}

async function deregister() {
  try {
    await fetch(\`\${REGISTRY_URL}/v1/agents/\${AGENT_ID}\`, { method: "DELETE" });
    console.log(\`[wwa] Deregistered agent '\${AGENT_ID}'\`);
  } catch {}
}

register();
process.on("SIGTERM", deregister);
process.on("SIGINT", deregister);
// ──────────────────────────────────────────────────────
`
      : `// Registration disabled. Set WWA_REGISTRY_URL to enable.`;

    return `/**
 * WWA Handoff adapter — ${options.agentId}
 *
 * Generated by wwa-cli for LangGraph (TypeScript).
 * Do not edit manually — regenerate with 'wwa init'.
 */

import http from "node:http";
import { randomUUID } from "node:crypto";

// Override registry URL at runtime
const REGISTRY_URL_ENV = process.env.WWA_REGISTRY_URL || "${options.registryUrl}";

const HANDOFF_ENDPOINT = "${options.endpoint}";

${regBlock}

// ── IACP Types ────────────────────────────────────────

interface IACPEnvelope {
  type: "request" | "response" | "event" | "error" | "heartbeat";
  intent: string;
  payload: Record<string, unknown>;
  correlation_id?: string;
}

interface IACPResponse {
  type: string;
  intent: string;
  status: string;
  payload: Record<string, unknown>;
  message_id: string;
  timestamp: string;
}

// ── IACP Message Handler ──────────────────────────────

function handleIacpMessage(envelope: IACPEnvelope): IACPResponse {
  const messageType = envelope.type || "request";
  const intent = envelope.intent || "handoff";

  if (intent === "handoff" && messageType === "request") {
    const task = envelope.payload || {};

    // Invoke your LangGraph here:
    // const result = await graph.invoke({ input: task.task_description, ... });

    return {
      type: "response",
      intent: "handoff",
      status: "completed",
      payload: {
        result: { message: "LangGraph invocation placeholder" },
        task_description: task.task_description,
      },
      message_id: randomUUID(),
      timestamp: new Date().toISOString(),
    };
  }

  if (intent === "health") {
    return {
      type: "heartbeat",
      intent: "health",
      status: "healthy",
      payload: { agent_id: AGENT_ID, endpoint: HANDOFF_ENDPOINT },
      message_id: randomUUID(),
      timestamp: new Date().toISOString(),
    };
  }

  return {
    type: "error",
    intent,
    status: "unknown_intent",
    payload: { error: \`Intent '\${intent}' not supported\` },
    message_id: randomUUID(),
    timestamp: new Date().toISOString(),
  };
}

// ── HTTP Server ───────────────────────────────────────

const [host, portStr] = HANDOFF_ENDPOINT.split(":");
const port = parseInt(portStr || "8787", 10);

const server = http.createServer(async (req, res) => {
  // CORS
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, X-Agent-ID");

  if (req.method === "OPTIONS") {
    res.writeHead(204);
    res.end();
    return;
  }

  if (req.method === "GET" && req.url === "/health") {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ status: "healthy", agent_id: AGENT_ID }));
    return;
  }

  if (req.method === "POST" && req.url === "/iacp/message") {
    let body = "";
    for await (const chunk of req) {
      body += chunk;
    }
    try {
      const envelope: IACPEnvelope = JSON.parse(body);
      const response = handleIacpMessage(envelope);
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify(response));
    } catch (e: any) {
      res.writeHead(400, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: "Invalid IACP envelope", detail: e.message }));
    }
    return;
  }

  res.writeHead(404);
  res.end();
});

server.listen(port, () => {
  console.log(\`[wwa] IACP listener ready at http://\${HANDOFF_ENDPOINT}/iacp/message\`);
});

export { handleIacpMessage, server };
`;
  }

  private generateManifest(options: GeneratorOptions, includeIdentity: boolean = true): string {
    const identityBlock = includeIdentity
      ? `\nidentity:
  agent_id: "${options.agentId}"
  protocol: identity/v1.1.0`
      : "";
    const iacpBlock = !options.capabilities || options.capabilities.includes("iacp")
      ? `\niacp:
  endpoint: "/iacp/message"
  intents:
    - handoff
    - health`
      : "";

    return `# WWA Capability Manifest — ${options.agentId}
# Generated by wwa-cli for LangGraph

manifest_version: "1.0.0"
agent_id: "${options.agentId}"
framework: langgraph
endpoint: "${options.endpoint}"

capabilities:
  - action: langgraph_invoke
    target: iacp
    description: "Invoke LangGraph compiled graph via IACP"
    success_rate: 0.99
    avg_duration_seconds: 5

tools:
  - langgraph
  - iacp
  - http
${identityBlock}
${iacpBlock}
${options.registryUrl ? `registry:\n  url: "${options.registryUrl}"\n  auto_register: true\n  auto_deregister: true` : `registry:\n  auto_register: false`}
`;
  }
}
