/**
 * MCP Bridge Generator (Python + TypeScript)
 *
 * Generates an MCP→IACP bridge sidecar that exposes MCP tools/resources
 * as IACP capabilities and translates between the two protocols.
 * Also generates a handoff adapter for MCP-based agents.
 */

import * as path from "path";
import * as Handlebars from "handlebars";
import { Generator, GeneratorOptions, GeneratorResult, SupportedLanguage } from "./base";
import { detect } from "../detectors/detect";

export class MCPGenerator extends Generator {
  readonly framework = "mcp";

  get supportedLanguages(): SupportedLanguage[] {
    return ["python", "typescript"];
  }

  async detect(projectPath: string): Promise<boolean> {
    const info = detect(projectPath);
    // Detect MCP: look for mcp.json, iacp-mcp-bridge.py, or mcp-related deps
    if (info.possibleFrameworks.includes("mcp")) return true;

    // Also check for MCP-specific files
    const fs = await import("fs");
    const mcpConfigFiles = ["mcp.json", ".mcp.json", "mcp-config.json", "iacp-mcp-bridge.py"];
    for (const f of mcpConfigFiles) {
      if (fs.existsSync(path.join(projectPath, f))) return true;
    }
    return false;
  }

  async generate(
    projectPath: string,
    language: SupportedLanguage,
    options: GeneratorOptions,
  ): Promise<GeneratorResult[]> {
    const results: GeneratorResult[] = [];
    const caps = options.capabilities;
    const wantsBridge = !caps || caps.includes("iacp") || caps.includes("handoff");
    const wantsManifest = !caps || caps.includes("manifest");
    const wantsIdentity = !caps || caps.includes("identity");

    // Generate MCP→IACP bridge sidecar (Python)
    if (wantsBridge) {
      results.push({
        file: "iacp-mcp-bridge.py",
        content: this.generateMCPBridge(options, wantsIdentity),
      });
    }

    // Generate handoff adapter for MCP agents
    if (wantsBridge) {
      const ext = language === "python" ? "py" : "ts";
      results.push({
        file: `wwa_handoff.${ext}`,
        content: language === "python"
          ? this.generateMCPHandoffPython(options)
          : this.generateMCPHandoffTypeScript(options),
      });
    }

    // Generate manifest
    if (wantsManifest) {
      results.push({
        file: "manifest.yaml",
        content: this.generateManifest(options, wantsIdentity),
      });
    }

    return results;
  }

  private generateMCPBridge(options: GeneratorOptions, includeIdentity: boolean): string {
    const keyBlock = includeIdentity
      ? `
# ── Ed25519 Identity ──────────────────────────────────
# Generate keys: python3 -c "
# from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
# key = Ed25519PrivateKey.generate()
# print('PRIVATE_KEY=' + key.private_bytes_raw().hex())
# print('PUBLIC_KEY=' + key.public_key().public_bytes_raw().hex())
# "
import os as _os

_private_key_hex = _os.environ.get("IACP_PRIVATE_KEY", "")
_public_key_hex = _os.environ.get("IACP_PUBLIC_KEY", "")

def sign_message(message_bytes: bytes) -> bytes:
    """Sign an IACP message with Ed25519."""
    if not _private_key_hex:
        return b""  # No signing key configured
    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
        key = Ed25519PrivateKey.from_private_bytes(bytes.fromhex(_private_key_hex))
        return key.sign(message_bytes)
    except Exception:
        return b""
`
      : `# Identity signing disabled. Set IACP_PRIVATE_KEY to enable Ed25519 signing.`;

    return `#!/usr/bin/env python3
"""
IACP ↔ MCP Bridge Sidecar — ${options.agentId}

Generated by wwa-cli for MCP-based agents.

Bridges MCP tools/resources into IACP capabilities and vice versa.
Supports --transport mcp and --transport iacp for asymmetric deployments.

Usage:
  python3 iacp-mcp-bridge.py --transport both --port 8787
  python3 iacp-mcp-bridge.py --transport mcp --port 8787
  python3 iacp-mcp-bridge.py --transport iacp --port 8787
"""

import argparse
import json
import uuid
import sys
from datetime import datetime, timezone
from http.server import HTTPServer, BaseHTTPRequestHandler
from typing import Optional, Dict, Any, List
${keyBlock}

# ── Configuration ─────────────────────────────────────
MCP_COMMAND = "${options.endpoint}"
IACP_ENDPOINT = "${options.endpoint}"
AGENT_ID = "${options.agentId}"

# ── MCP Tool Registry ────────────────────────────────
# Define MCP tools that are exposed as IACP capabilities
MCP_TOOLS: Dict[str, Dict[str, Any]] = {
    "mcp_echo": {
        "description": "Echo back the input — MCP test tool",
        "parameters": {"message": "string"},
        "handler": lambda params: {"result": params.get("message", "")},
    },
    "mcp_health": {
        "description": "Health check for the MCP bridge",
        "parameters": {},
        "handler": lambda params: {"status": "healthy", "bridge": "iacp-mcp", "agent_id": AGENT_ID},
    },
}

MCP_RESOURCES: Dict[str, Dict[str, Any]] = {
    "bridge_info": {
        "description": "Bridge metadata resource",
        "mime_type": "application/json",
        "handler": lambda: json.dumps({
            "version": "1.0.0",
            "agent_id": AGENT_ID,
            "endpoint": IACP_ENDPOINT,
            "tools": list(MCP_TOOLS.keys()),
        }),
    },
}

# ── IACP Message Types ────────────────────────────────
class IACPEnvelope:
    """Standard IACP message envelope."""
    def __init__(self, msg_type: str, intent: str, payload: Dict[str, Any],
                 correlation_id: Optional[str] = None):
        self.type = msg_type
        self.intent = intent
        self.payload = payload
        self.message_id = str(uuid.uuid4())
        self.timestamp = datetime.now(timezone.utc).isoformat()
        self.correlation_id = correlation_id

    def to_dict(self) -> Dict[str, Any]:
        d = {
            "type": self.type,
            "intent": self.intent,
            "payload": self.payload,
            "message_id": self.message_id,
            "timestamp": self.timestamp,
        }
        if self.correlation_id:
            d["correlation_id"] = self.correlation_id
        return d

    def sign(self) -> Dict[str, Any]:
        """Sign the envelope with Ed25519."""
        d = self.to_dict()
        canonical = json.dumps(d, sort_keys=True).encode()
        sig = sign_message(canonical)
        if sig:
            d["signature"] = sig.hex()
            if _public_key_hex:
                d["public_key"] = _public_key_hex
        return d


# ── MCP Request Handler ───────────────────────────────
def handle_mcp_request(request: Dict[str, Any]) -> Dict[str, Any]:
    """Process an MCP request and return an MCP response."""
    method = request.get("method", "")
    req_id = request.get("id", str(uuid.uuid4()))

    if method == "tools/list":
        tools = []
        for name, info in MCP_TOOLS.items():
            tools.append({
                "name": name,
                "description": info["description"],
                "inputSchema": {
                    "type": "object",
                    "properties": {k: {"type": v} for k, v in info.get("parameters", {}).items()},
                },
            })
        return {"jsonrpc": "2.0", "id": req_id, "result": {"tools": tools}}

    if method == "resources/list":
        resources = []
        for name, info in MCP_RESOURCES.items():
            resources.append({
                "uri": f"mcp://{AGENT_ID}/{name}",
                "name": name,
                "description": info["description"],
                "mimeType": info["mime_type"],
            })
        return {"jsonrpc": "2.0", "id": req_id, "result": {"resources": resources}}

    if method == "tools/call":
        params = request.get("params", {})
        tool_name = params.get("name", "")
        tool_args = params.get("arguments", {})

        if tool_name in MCP_TOOLS:
            try:
                result = MCP_TOOLS[tool_name]["handler"](tool_args)
                return {"jsonrpc": "2.0", "id": req_id, "result": {"content": [{"type": "text", "text": json.dumps(result)}]}}
            except Exception as e:
                return {"jsonrpc": "2.0", "id": req_id, "error": {"code": -1, "message": str(e)}}

        return {"jsonrpc": "2.0", "id": req_id, "error": {"code": -32601, "message": f"Tool '{tool_name}' not found"}}

    if method == "resources/read":
        params = request.get("params", {})
        uri = params.get("uri", "")
        resource_name = uri.split("/")[-1] if "/" in uri else uri

        if resource_name in MCP_RESOURCES:
            try:
                content = MCP_RESOURCES[resource_name]["handler"]()
                return {"jsonrpc": "2.0", "id": req_id, "result": {"contents": [{"uri": uri, "mimeType": MCP_RESOURCES[resource_name]["mime_type"], "text": content}]}}
            except Exception as e:
                return {"jsonrpc": "2.0", "id": req_id, "error": {"code": -1, "message": str(e)}}

        return {"jsonrpc": "2.0", "id": req_id, "error": {"code": -32602, "message": f"Resource '{resource_name}' not found"}}

    return {"jsonrpc": "2.0", "id": req_id, "error": {"code": -32601, "message": f"Method '{method}' not supported"}}


# ── IACP → MCP Translation ────────────────────────────
def handle_iacp_message(envelope: Dict[str, Any]) -> Dict[str, Any]:
    """Translate an IACP message into MCP calls and back."""
    intent = envelope.get("intent", "handoff")
    msg_type = envelope.get("type", "request")
    payload = envelope.get("payload", {})

    if intent == "handoff" and msg_type == "request":
        # Translate IACP handoff into MCP tool call
        mcp_request = {
            "jsonrpc": "2.0",
            "method": "tools/call",
            "id": str(uuid.uuid4()),
            "params": {
                "name": payload.get("tool", "mcp_echo"),
                "arguments": payload.get("arguments", payload),
            },
        }
        mcp_response = handle_mcp_request(mcp_request)

        envelope_response = IACPEnvelope("response", "handoff", {
            "mcp_response": mcp_response,
            "result": mcp_response.get("result", {}),
        }, correlation_id=envelope.get("correlation_id"))
        return envelope_response.sign()

    if intent == "discover":
        # List available MCP tools as IACP capabilities
        tools_list = list(MCP_TOOLS.keys())
        resources_list = list(MCP_RESOURCES.keys())
        envelope_response = IACPEnvelope("response", "discover", {
            "agent_id": AGENT_ID,
            "capabilities": [
                {"action": f"mcp:{t}", "target": "iacp", "description": MCP_TOOLS[t]["description"]}
                for t in tools_list
            ],
            "resources": resources_list,
            "protocols": ["mcp", "iacp"],
        }, correlation_id=envelope.get("correlation_id"))
        return envelope_response.sign()

    if intent == "health":
        envelope_response = IACPEnvelope("heartbeat", "health", {
            "agent_id": AGENT_ID,
            "status": "healthy",
            "bridge_version": "1.0.0",
            "mcp_tools": len(MCP_TOOLS),
            "mcp_resources": len(MCP_RESOURCES),
        }, correlation_id=envelope.get("correlation_id"))
        return envelope_response.sign()

    return IACPEnvelope("error", intent, {
        "error": f"Intent '{intent}' not supported",
        "agent_id": AGENT_ID,
    }, correlation_id=envelope.get("correlation_id")).sign()


# ── HTTP Handlers ──────────────────────────────────────
class MCPHandler(BaseHTTPRequestHandler):
    """HTTP handler for MCP JSON-RPC requests."""

    def do_POST(self):
        content_length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(content_length)

        try:
            request = json.loads(body)
            response = handle_mcp_request(request)
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(json.dumps(response).encode())
        except json.JSONDecodeError:
            self.send_response(400)
            self.end_headers()
            self.wfile.write(json.dumps({"error": "Invalid JSON"}).encode())

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()


class IACPHandler(BaseHTTPRequestHandler):
    """HTTP handler for IACP messages."""

    def do_POST(self):
        content_length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(content_length)

        try:
            envelope = json.loads(body)
            response = handle_iacp_message(envelope)
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(json.dumps(response).encode())
        except json.JSONDecodeError:
            self.send_response(400)
            self.end_headers()
            self.wfile.write(json.dumps({"error": "Invalid IACP envelope"}).encode())

    def do_GET(self):
        if self.path == "/health" or self.path == "/":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({
                "status": "healthy",
                "agent_id": AGENT_ID,
                "bridge": "iacp-mcp",
            }).encode())
        else:
            self.send_response(404)
            self.end_headers()

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()


class CombinedHandler(BaseHTTPRequestHandler):
    """Combined handler that routes MCP and IACP on the same port."""

    def do_POST(self):
        content_length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(content_length)

        try:
            data = json.loads(body)

            # Route: if it has "jsonrpc" → MCP, else → IACP
            if "jsonrpc" in data:
                response = handle_mcp_request(data)
            else:
                response = handle_iacp_message(data)

            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(json.dumps(response).encode())
        except json.JSONDecodeError:
            self.send_response(400)
            self.end_headers()
            self.wfile.write(json.dumps({"error": "Invalid JSON"}).encode())

    def do_GET(self):
        if self.path == "/health" or self.path == "/":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({
                "status": "healthy",
                "agent_id": AGENT_ID,
                "bridge": "iacp-mcp",
        "protocols": ["mcp", "iacp"],
            }).encode())
        else:
            self.send_response(404)
            self.end_headers()

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()


# ── Main ──────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="IACP ↔ MCP Bridge Sidecar")
    parser.add_argument("--transport", choices=["mcp", "iacp", "both"], default="both",
                        help="Transport mode: mcp (MCP server only), iacp (IACP server only), both (combined)")
    parser.add_argument("--port", type=int, default=8787, help="HTTP port (default: 8787)")
    parser.add_argument("--host", default="0.0.0.0", help="Bind address (default: 0.0.0.0)")
    parser.add_argument("--mcp-port", type=int, default=None, help="Separate port for MCP server")
    parser.add_argument("--iacp-port", type=int, default=None, help="Separate port for IACP server")
    args = parser.parse_args()

    print(f"[wwa] IACP ↔ MCP Bridge — {AGENT_ID}")
    print(f"[wwa] Transport mode: {args.transport}")

    if args.transport == "both" and not args.mcp_port and not args.iacp_port:
        # Single combined server
        server = HTTPServer((args.host, args.port), CombinedHandler)
        print(f"[wwa] Combined MCP+IACP server on http://{args.host}:{args.port}")
        print(f"[wwa]   MCP endpoint:  POST http://{args.host}:{args.port}")
        print(f"[wwa]   IACP endpoint: POST http://{args.host}:{args.port}/iacp/message")
        print(f"[wwa]   Health check:  GET  http://{args.host}:{args.port}/health")
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            print("\\n[wwa] Shutting down...")
            server.shutdown()

    elif args.transport == "mcp":
        port = args.mcp_port or args.port
        server = HTTPServer((args.host, port), MCPHandler)
        print(f"[wwa] MCP server on http://{args.host}:{port}")
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            print("\\n[wwa] Shutting down...")
            server.shutdown()

    elif args.transport == "iacp":
        port = args.iacp_port or args.port
        server = HTTPServer((args.host, port), IACPHandler)
        print(f"[wwa] IACP server on http://{args.host}:{port}")
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            print("\\n[wwa] Shutting down...")
            server.shutdown()

if __name__ == "__main__":
    main()
`;
  }

  private generateMCPHandoffPython(options: GeneratorOptions): string {
    const regBlock = options.registryUrl
      ? `
# ── WWA Registry Auto-Registration ─────────────────────
import atexit, urllib.request, json as _json

REGISTRY_URL = "${options.registryUrl}"
HANDOFF_ENDPOINT = "${options.endpoint}"
_AGENT_ID = "${options.agentId}"

def _register():
    try:
        req = urllib.request.Request(
            f"{REGISTRY_URL}/v1/agents/register",
            data=_json.dumps({
                "manifest_version": "1.0.0",
                "agent_id": _AGENT_ID,
                "capabilities": [{"action": "mcp_handoff", "target": "iacp"}],
                "tools": ["mcp", "iacp"],
                "endpoint": {"address": HANDOFF_ENDPOINT, "protocol": "acp"},
                "status": {"state": "healthy", "load": 0.0, "current_tasks": 0, "max_tasks": 10}
            }).encode(),
            headers={"Content-Type": "application/json"}
        )
        urllib.request.urlopen(req)
        print(f"[wwa] Registered '{_AGENT_ID}'")
    except Exception as e:
        print(f"[wwa] Registration skipped: {e}")

def _deregister():
    try:
        urllib.request.urlopen(urllib.request.Request(f"{REGISTRY_URL}/v1/agents/{_AGENT_ID}", method="DELETE"))
    except: pass

_register()
atexit.register(_deregister)
`
      : `# Registration disabled.`;

    return `"""
WWA Handoff Adapter — ${options.agentId}
Generated by wwa-cli for MCP-based agents.

Integrates MCP tools into the WWA handoff protocol.
"""
import os, json, uuid
from datetime import datetime, timezone

HANDOFF_ENDPOINT = "${options.endpoint}"
AGENT_ID = "${options.agentId}"
${regBlock}

# Try to import the MCP bridge
try:
    from iacp_mcp_bridge import handle_iacp_message as bridge_handle
except ImportError:
    bridge_handle = None
    print("[wwa] iacp-mcp-bridge not found — using built-in handler")

def handle_iacp_message(envelope: dict) -> dict:
    """Process an IACP handoff request through MCP tools."""
    if bridge_handle:
        return bridge_handle(envelope)

    intent = envelope.get("intent", "handoff")
    msg_type = envelope.get("type", "request")

    if intent == "handoff" and msg_type == "request":
        task = envelope.get("payload", {})
        return {
            "type": "response",
            "intent": "handoff",
            "status": "completed",
            "payload": {
                "result": f"MCP agent '{AGENT_ID}' processed: {task.get('task_description', 'unknown task')}",
                "agent_id": AGENT_ID,
            },
            "message_id": str(uuid.uuid4()),
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

    if intent == "health":
        return {
            "type": "heartbeat",
            "intent": "health",
            "status": "healthy",
            "payload": {"agent_id": AGENT_ID, "endpoint": HANDOFF_ENDPOINT},
            "message_id": str(uuid.uuid4()),
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

    return {
        "type": "error",
        "intent": intent,
        "status": "unknown_intent",
        "payload": {"error": f"Intent '{intent}' not supported"},
        "message_id": str(uuid.uuid4()),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }

# FastAPI server
try:
    from fastapi import FastAPI
    from fastapi.middleware.cors import CORSMiddleware
    app = FastAPI(title=f"WWA MCP Adapter: {AGENT_ID}")
    app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])
    @app.post("/iacp/message")
    async def iacp_message(envelope: dict): return handle_iacp_message(envelope)
    @app.get("/health")
    async def health(): return {"status": "healthy", "agent_id": AGENT_ID}
    print(f"[wwa] IACP listener ready at http://{HANDOFF_ENDPOINT}/iacp/message")
except ImportError:
    print("[wwa] FastAPI not installed. pip install fastapi uvicorn")
`;
  }

  private generateMCPHandoffTypeScript(options: GeneratorOptions): string {
    const regBlock = options.registryUrl
      ? `
// ── WWA Registry Auto-Registration ────────────────────
const REGISTRY_URL = "${options.registryUrl}";
const AGENT_ID = "${options.agentId}";
const ENDPOINT = "${options.endpoint}";

async function register() {
  try {
    await fetch(\`\${REGISTRY_URL}/v1/agents/register\`, {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        manifest_version: "1.0.0", agent_id: AGENT_ID,
        capabilities: [{ action: "mcp_handoff", target: "iacp" }],
        tools: ["mcp", "iacp"],
        endpoint: { address: ENDPOINT, protocol: "acp" },
        status: { state: "healthy", load: 0, current_tasks: 0, max_tasks: 10 }
      }),
    });
    console.log(\`[wwa] Registered '\${AGENT_ID}'\`);
  } catch (e) { console.log(\`[wwa] Registration skipped: \${e}\`); }
}
async function deregister() {
  try { await fetch(\`\${REGISTRY_URL}/v1/agents/\${AGENT_ID}\`, { method: "DELETE" }); } catch {}
}
register();
process.on("SIGTERM", deregister);
process.on("SIGINT", deregister);`
      : `// Registration disabled.`;

    return `/**
 * WWA Handoff Adapter — ${options.agentId}
 * Generated by wwa-cli for MCP-based agents (TypeScript).
 */
import http from "node:http";
import { randomUUID } from "node:crypto";

const HANDOFF_ENDPOINT = "${options.endpoint}";
${regBlock}

interface IACPEnvelope {
  type: string; intent: string; payload: Record<string, unknown>;
}

interface IACPResponse {
  type: string; intent: string; status: string;
  payload: Record<string, unknown>; message_id: string; timestamp: string;
}

function handleIacpMessage(envelope: IACPEnvelope): IACPResponse {
  const intent = envelope.intent || "handoff";
  if (intent === "handoff" && envelope.type === "request") {
    const task = envelope.payload || {};
    return {
      type: "response", intent: "handoff", status: "completed",
      payload: {
        result: \`MCP agent processed: \${task.task_description || "unknown"}\`,
        agent_id: AGENT_ID,
      },
      message_id: randomUUID(), timestamp: new Date().toISOString(),
    };
  }
  if (intent === "health") {
    return {
      type: "heartbeat", intent: "health", status: "healthy",
      payload: { agent_id: AGENT_ID, endpoint: HANDOFF_ENDPOINT },
      message_id: randomUUID(), timestamp: new Date().toISOString(),
    };
  }
  return {
    type: "error", intent, status: "unknown_intent",
    payload: { error: \`Intent '\${intent}' not supported\` },
    message_id: randomUUID(), timestamp: new Date().toISOString(),
  };
}

const [host, portStr] = HANDOFF_ENDPOINT.split(":");
const port = parseInt(portStr || "8787", 10);
const server = http.createServer(async (req, res) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  if (req.method === "OPTIONS") { res.writeHead(204); res.end(); return; }
  if (req.method === "GET" && req.url === "/health") {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ status: "healthy", agent_id: AGENT_ID }));
    return;
  }
  if (req.method === "POST" && req.url === "/iacp/message") {
    let body = "";
    for await (const chunk of req) body += chunk;
    try {
      const response = handleIacpMessage(JSON.parse(body));
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify(response));
    } catch (e: any) {
      res.writeHead(400, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: "Invalid IACP envelope", detail: e.message }));
    }
    return;
  }
  res.writeHead(404); res.end();
});
server.listen(port, () => console.log(\`[wwa] IACP listener at http://\${HANDOFF_ENDPOINT}/iacp/message\`));

export { handleIacpMessage, server };
`;
  }

  private generateManifest(options: GeneratorOptions, includeIdentity: boolean = true): string {
    const identityBlock = includeIdentity
      ? `\nidentity:\n  agent_id: "${options.agentId}"\n  protocol: identity/v1.1.0`
      : "";
    const reg = options.registryUrl
      ? `registry:\n  url: "${options.registryUrl}"\n  auto_register: true\n  auto_deregister: true`
      : `registry:\n  auto_register: false`;

    return `# WWA Capability Manifest — ${options.agentId}
manifest_version: "1.0.0"
agent_id: "${options.agentId}"
framework: mcp
endpoint: "${options.endpoint}"

capabilities:
  - action: mcp_bridge
    target: iacp
    description: "MCP→IACP protocol bridge"
  - action: mcp_handoff
    target: iacp
    description: "MCP agent handoff via IACP"

tools:
  - mcp
  - iacp
  - bridge

mcp_bridge:
  endpoint: "/"
  transports:
    - mcp
    - iacp
  signing: ed25519
${identityBlock}
iacp:
  endpoint: "/iacp/message"
  intents:
    - handoff
    - discover
    - health

${reg}
`;
  }
}
