/**
 * OpenAI Agents SDK Generator (Python + TypeScript)
 *
 * Wraps an OpenAI Runner/Agent as a WWA-compatible IACP node.
 * Both Python and TypeScript supported.
 */

import * as path from "path";
import * as fs from "fs";
import * as Handlebars from "handlebars";
import { Generator, GeneratorOptions, GeneratorResult, SupportedLanguage } from "./base";
import { detect } from "../detectors/detect";

export class OpenAIAgentsGenerator extends Generator {
  readonly framework = "openai_agents";

  get supportedLanguages(): SupportedLanguage[] {
    return ["python", "typescript"];
  }

  async detect(projectPath: string): Promise<boolean> {
    const info = detect(projectPath);
    return info.framework === "openai_agents";
  }

  async generate(
    projectPath: string,
    language: SupportedLanguage,
    options: GeneratorOptions,
  ): Promise<GeneratorResult[]> {
    const results: GeneratorResult[] = [];
    const caps = options.capabilities;
    const wantsIacpOrHandoff = !caps || caps.includes("iacp") || caps.includes("handoff");
    const wantsManifest = !caps || caps.includes("manifest");
    const wantsIdentity = !caps || caps.includes("identity");

    if (wantsIacpOrHandoff) {
      const ext = language === "python" ? "py" : "ts";
      results.push({
        file: `wwa_handoff.${ext}`,
        content: language === "python"
          ? this.generatePythonAdapter(options)
          : this.generateTypeScriptAdapter(options),
      });
    }

    if (wantsManifest) {
      results.push({
        file: "manifest.yaml",
        content: this.generateManifest(options, wantsIdentity),
      });
    }

    return results;
  }

  private generatePythonAdapter(options: GeneratorOptions): string {
    const regBlock = options.registryUrl
      ? `
REGISTRY_URL = "${options.registryUrl}"
AGENT_ID = "${options.agentId}"
ENDPOINT = "${options.endpoint}"

import atexit, urllib.request, json as _json
def _register():
    try:
        req = urllib.request.Request(f"{REGISTRY_URL}/v1/agents/register",
            data=_json.dumps({"manifest_version":"1.0.0","agent_id":AGENT_ID,"capabilities":[{"action":"openai_run","target":"iacp"}],"tools":["openai","iacp"],"endpoint":{"address":ENDPOINT,"protocol":"acp"},"status":{"state":"healthy","load":0,"current_tasks":0,"max_tasks":10}}).encode(),
            headers={"Content-Type":"application/json"})
        urllib.request.urlopen(req)
        print(f"[wwa] Registered '{AGENT_ID}'")
    except Exception as e: print(f"[wwa] Registration skipped: {e}")
def _deregister():
    try: urllib.request.urlopen(urllib.request.Request(f"{REGISTRY_URL}/v1/agents/{AGENT_ID}", method="DELETE"))
    except: pass
_register(); atexit.register(_deregister)`
      : `# Registration disabled.`;

    return `"""
WWA Handoff adapter — ${options.agentId}
Generated by wwa-cli for OpenAI Agents SDK.
"""
import os, json, uuid
from datetime import datetime, timezone

HANDOFF_ENDPOINT = "${options.endpoint}"
AGENT_ID = "${options.agentId}"
${regBlock}

# Import your OpenAI agent:
# from agents import Agent, Runner
# my_agent = Agent(name="...", model="gpt-4o", ...)
try:
    from agents import Runner
except ImportError:
    Runner = None
    print("[wwa] openai-agents SDK not installed: pip install openai-agents")

def handle_iacp_message(envelope: dict) -> dict:
    intent = envelope.get("intent", "handoff")
    if intent == "handoff" and envelope.get("type") == "request":
        task = envelope.get("payload", {})
        if Runner:
            try:
                from agents import Agent
                # Create a temporary agent for the task
                agent = Agent(
                    name=AGENT_ID,
                    instructions=task.get("task_description", "Process the IACP request"),
                    model=os.environ.get("OPENAI_MODEL", "gpt-4o"),
                )
                result = Runner.run_sync(agent, task.get("task_description", ""))
                return {"type":"response","intent":"handoff","status":"completed",
                    "payload":{"result":result.final_output if hasattr(result,'final_output') else str(result)},
                    "message_id":str(uuid.uuid4()),"timestamp":datetime.now(timezone.utc).isoformat()}
            except Exception as e:
                return {"type":"error","intent":"handoff","status":"invoke_failed",
                    "payload":{"error":str(e)},"message_id":str(uuid.uuid4()),"timestamp":datetime.now(timezone.utc).isoformat()}
        else:
            return {"type":"response","intent":"handoff","status":"completed",
                "payload":{"result":"OpenAI Agents SDK not available"},"message_id":str(uuid.uuid4()),
                "timestamp":datetime.now(timezone.utc).isoformat()}
    return {"type":"error","intent":intent,"status":"unknown_intent",
        "payload":{"error":f"Intent '{intent}' not supported"},"message_id":str(uuid.uuid4()),
        "timestamp":datetime.now(timezone.utc).isoformat()}

# FastAPI server
try:
    from fastapi import FastAPI
    from fastapi.middleware.cors import CORSMiddleware
    app = FastAPI(title=f"WWA OpenAI Adapter: {AGENT_ID}")
    app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])
    @app.post("/iacp/message")
    async def iacp_message(envelope: dict): return handle_iacp_message(envelope)
    @app.get("/health")
    async def health(): return {"status":"healthy","agent_id":AGENT_ID}
    print(f"[wwa] IACP listener ready at http://{HANDOFF_ENDPOINT}/iacp/message")
except ImportError:
    print("[wwa] FastAPI not installed. pip install fastapi uvicorn")
`;
  }

  private generateTypeScriptAdapter(options: GeneratorOptions): string {
    const regBlock = options.registryUrl
      ? `
const REGISTRY_URL = "${options.registryUrl}";
const AGENT_ID = "${options.agentId}";
const ENDPOINT = "${options.endpoint}";

async function register() {
  try {
    await fetch(\`\${REGISTRY_URL}/v1/agents/register\`, {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ manifest_version: "1.0.0", agent_id: AGENT_ID,
        capabilities: [{ action: "openai_run", target: "iacp" }], tools: ["openai", "iacp"],
        endpoint: { address: ENDPOINT, protocol: "acp" },
        status: { state: "healthy", load: 0, current_tasks: 0, max_tasks: 10 } }),
    });
    console.log(\`[wwa] Registered '\${AGENT_ID}'\`);
  } catch (e) { console.log(\`[wwa] Registration skipped: \${e}\`); }
}
async function deregister() {
  try { await fetch(\`\${REGISTRY_URL}/v1/agents/\${AGENT_ID}\`, { method: "DELETE" }); } catch {}
}
register();
process.on("SIGTERM", deregister);
process.on("SIGINT", deregister);`
      : `// Registration disabled.`;

    return `/**
 * WWA Handoff adapter — ${options.agentId}
 * Generated by wwa-cli for OpenAI Agents SDK (TypeScript).
 */
import http from "node:http";
import { randomUUID } from "node:crypto";

const HANDOFF_ENDPOINT = "${options.endpoint}";
${regBlock}

interface IACPEnvelope {
  type: string; intent: string; payload: Record<string, unknown>;
}

interface IACPResponse {
  type: string; intent: string; status: string;
  payload: Record<string, unknown>; message_id: string; timestamp: string;
}

function handleIacpMessage(envelope: IACPEnvelope): IACPResponse {
  const intent = envelope.intent || "handoff";
  if (intent === "handoff" && envelope.type === "request") {
    // Placeholder — integrate your OpenAI SDK:
    // import OpenAI from "openai";
    // const openai = new OpenAI();
    return {
      type: "response", intent: "handoff", status: "completed",
      payload: { result: "OpenAI agent invocation placeholder" },
      message_id: randomUUID(), timestamp: new Date().toISOString(),
    };
  }
  return {
    type: "error", intent, status: "unknown_intent",
    payload: { error: \`Intent '\${intent}' not supported\` },
    message_id: randomUUID(), timestamp: new Date().toISOString(),
  };
}

const [host, portStr] = HANDOFF_ENDPOINT.split(":");
const port = parseInt(portStr || "8787", 10);
const server = http.createServer(async (req, res) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  if (req.method === "OPTIONS") { res.writeHead(204); res.end(); return; }
  if (req.method === "GET" && req.url === "/health") {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ status: "healthy", agent_id: AGENT_ID }));
    return;
  }
  if (req.method === "POST" && req.url === "/iacp/message") {
    let body = "";
    for await (const chunk of req) body += chunk;
    try {
      const response = handleIacpMessage(JSON.parse(body));
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify(response));
    } catch (e: any) {
      res.writeHead(400, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: "Invalid IACP envelope", detail: e.message }));
    }
    return;
  }
  res.writeHead(404); res.end();
});
server.listen(port, () => console.log(\`[wwa] IACP listener at http://\${HANDOFF_ENDPOINT}/iacp/message\`));

export { handleIacpMessage, server };
`;
  }

  private generateManifest(options: GeneratorOptions, includeIdentity: boolean = true): string {
    const identityBlock = includeIdentity
      ? `\nidentity:\n  agent_id: "${options.agentId}"\n  protocol: identity/v1.1.0`
      : "";
    const reg = options.registryUrl
      ? `registry:\n  url: "${options.registryUrl}"\n  auto_register: true\n  auto_deregister: true`
      : `registry:\n  auto_register: false`;

    return `# WWA Capability Manifest — ${options.agentId}
manifest_version: "1.0.0"
agent_id: "${options.agentId}"
framework: openai_agents
endpoint: "${options.endpoint}"

capabilities:
  - action: openai_run
    target: iacp
    description: "Run OpenAI agent via IACP"

tools:
  - openai
  - iacp
${identityBlock}
iacp:
  endpoint: "/iacp/message"
  intents:
    - handoff
    - health

${reg}
`;
  }
}
