import { SetupOptions, SetupOutput } from "./base";

const DO_SCRIPT = (opts: SetupOptions) => `#!/usr/bin/env bash
# WWA DigitalOcean Setup — generated by wwa-cli
# Provisions a $6 or $12 droplet, installs Docker, deploys WWA registry + gateway.
#
# Prerequisites:
#   1. DigitalOcean account with SSH key uploaded
#   2. doctl CLI installed & authenticated: doctl auth init
#   3. SSH key fingerprint (get it: doctl compute ssh-key list)
#
# Usage:
#   chmod +x wwa-digitalocean-setup.sh
#   ./wwa-digitalocean-setup.sh

set -euo pipefail

# ── Config ─────────────────────────────────────────────────────────
DROPLET_NAME="${opts.agentId || "wwa-registry"}"
SIZE="${opts.region == "fra1" ? "s-1vcpu-1gb" : "s-1vcpu-1gb"}"
REGION="${opts.region || "fra1"}"
IMAGE="ubuntu-24-04-x64"
SSH_KEY="${opts.sshKey || ""}"

echo "==> WWA DigitalOcean Setup"
echo "    Droplet: $DROPLET_NAME ($SIZE @ $REGION)"
echo ""

# ── Create droplet ─────────────────────────────────────────────────
echo "==> Creating droplet..."
ARGS=(
  --size "$SIZE"
  --region "$REGION"
  --image "$IMAGE"
  --tag-name wwa
)
[ -n "$SSH_KEY" ] && ARGS+=(--ssh-keys "$SSH_KEY")

DROPLET_ID=$(doctl compute droplet create "$DROPLET_NAME" "\${ARGS[@]}" --format ID --no-header 2>/dev/null | head -1)
echo "    Droplet ID: $DROPLET_ID"

# ── Wait for IP ────────────────────────────────────────────────────
echo "==> Waiting for IP..."
for i in $(seq 1 30); do
  IP=$(doctl compute droplet get "$DROPLET_ID" --format PublicIPv4 --no-header 2>/dev/null)
  if [ -n "$IP" ]; then
    echo "    IP: $IP (after \${i}s)"
    break
  fi
  sleep 2
done

# ── Wait for SSH ──────────────────────────────────────────────────
echo "==> Waiting for SSH..."
for i in $(seq 1 30); do
  if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 "root@$IP" "echo ok" 2>/dev/null; then
    echo "    SSH ready after \${i}s"
    break
  fi
  sleep 5
done

# ── Install Docker ─────────────────────────────────────────────────
echo "==> Installing Docker..."
ssh "root@$IP" << 'REMOTE'
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable docker
  systemctl start docker
REMOTE

# ── Deploy WWA stack ───────────────────────────────────────────────
echo "==> Deploying WWA stack..."
ssh "root@$IP" 'docker compose -p wwa up -d' << 'COMPOSE'
version: "3.9"
services:
  registry:
    image: workswithagents/registry:latest
    container_name: wwa-registry
    ports:
      - "3210:3210"
    volumes:
      - wwa-data:/data
    restart: unless-stopped
  gateway:
    image: workswithagents/gateway:latest
    container_name: wwa-gateway
    ports:
      - "8787:8787"
    environment:
      - REGISTRY_URL=http://registry:3210
    depends_on: [registry]
    restart: unless-stopped
volumes:
  wwa-data:
COMPOSE

# ── Firewall ───────────────────────────────────────────────────────
echo "==> Configuring firewall..."
ssh "root@$IP" << 'REMOTE'
  ufw --force disable
  ufw default deny incoming
  ufw default allow outgoing
  ufw allow ssh
  ufw allow 3210/tcp comment "WWA Registry"
  ufw allow 8787/tcp comment "WWA Gateway"
  ufw --force enable
REMOTE

echo ""
echo "==> ✅ WWA stack deployed!"
echo "    Droplet IP: $IP"
echo "    Registry:   http://$IP:3210"
echo "    Gateway:    http://$IP:8787"
echo ""
echo "    Configure your agent:"
echo "    export WWA_REGISTRY_URL=http://$IP:3210"
echo "    export IACP_ENDPOINT=$IP:8787"
echo ""
`;

export async function generateDOSetup(opts: SetupOptions): Promise<SetupOutput> {
  const scriptPath = `${opts.projectDir}/wwa-digitalocean-setup.sh`;
  const content = DO_SCRIPT(opts);

  const { writeFile, mkdir } = await import("fs/promises");
  await mkdir(opts.projectDir, { recursive: true });
  await writeFile(scriptPath, content, "utf-8");
  try {
    const { chmod } = await import("fs/promises");
    await chmod(scriptPath, 0o755);
  } catch { /* non-fatal */ }

  return {
    filesWritten: [scriptPath],
    instructions: [
      "WWA DigitalOcean setup generated!",
      "",
      "Prerequisites:",
      "  1. DigitalOcean account with SSH key uploaded",
      "  2. doctl CLI: https://docs.digitalocean.com/reference/doctl/",
      "  3. Run: doctl auth init",
      "",
      "To deploy:",
      `  chmod +x ${scriptPath}`,
      `  SSH_KEY=<your-key-fingerprint> ${scriptPath}`,
      "",
      "What it does:",
      "  - Creates $6 droplet ($SIZE) in $REGION",
      "  - Installs Docker + Docker Compose",
      "  - Deploys WWA Registry (port 3210)",
      "  - Deploys WWA Gateway (port 8787)",
      "  - Configures UFW firewall",
      "  - Prints connection details",
    ].join("\n"),
  };
}
