import { SetupOptions, SetupOutput } from "./base";

const HETZNER_SCRIPT = (opts: SetupOptions) => `#!/usr/bin/env bash
# WWA Hetzner Setup — generated by wwa-cli
# Provisions a CX23 VPS, installs Docker, deploys WWA registry + gateway.
#
# Prerequisites:
#   1. Hetzner account with SSH key uploaded
#   2. Hetzner API token (read:write) — set via HCLOUD_TOKEN or paste below
#   3. \`hcloud\` CLI installed (https://github.com/hetznercloud/cli)
#
# Usage:
#   chmod +x wwa-hetzner-setup.sh
#   HCLOUD_TOKEN=your_token ./wwa-hetzner-setup.sh

set -euo pipefail

# ── Config ─────────────────────────────────────────────────────────
SERVER_NAME="${opts.agentId || "wwa-registry"}"
SERVER_TYPE="cx23"
LOCATION="${opts.region || "nbg1"}"
IMAGE="ubuntu-24.04"
SSH_KEY="${opts.sshKey || ""}"

echo "==> WWA Hetzner Setup"
echo "    Server:  $SERVER_NAME ($SERVER_TYPE @ $LOCATION)"
echo "    Image:   $IMAGE"
echo ""

# ── Create server ──────────────────────────────────────────────────
echo "==> Creating server..."
HCLOUD_TOKEN="\${HCLOUD_TOKEN:?HCLOUD_TOKEN required}"
ARGS=(
  --name "$SERVER_NAME"
  --type "$SERVER_TYPE"
  --location "$LOCATION"
  --image "$IMAGE"
)
[ -n "$SSH_KEY" ] && ARGS+=(--ssh-key "$SSH_KEY")

hcloud server create "\${ARGS[@]}"

IP=$(hcloud server ip "$SERVER_NAME")
echo "    IP: $IP"
echo ""

# ── Wait for SSH ──────────────────────────────────────────────────
echo "==> Waiting for SSH..."
for i in $(seq 1 30); do
  if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 "root@$IP" "echo ok" 2>/dev/null; then
    echo "    SSH ready after \${i}s"
    break
  fi
  sleep 2
done

# ── Install Docker ─────────────────────────────────────────────────
echo "==> Installing Docker..."
ssh "root@$IP" << 'REMOTE'
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable docker
  systemctl start docker
REMOTE

# ── Deploy WWA stack ───────────────────────────────────────────────
echo "==> Deploying WWA stack..."
ssh "root@$IP" 'docker compose -p wwa up -d' << 'COMPOSE'
version: "3.9"
services:
  registry:
    image: workswithagents/registry:latest
    container_name: wwa-registry
    ports:
      - "3210:3210"
    volumes:
      - wwa-data:/data
    restart: unless-stopped
  gateway:
    image: workswithagents/gateway:latest
    container_name: wwa-gateway
    ports:
      - "8787:8787"
    environment:
      - REGISTRY_URL=http://registry:3210
    depends_on: [registry]
    restart: unless-stopped
volumes:
  wwa-data:
COMPOSE

# ── Firewall ───────────────────────────────────────────────────────
echo "==> Configuring firewall..."
ssh "root@$IP" << 'REMOTE'
  ufw --force disable
  ufw default deny incoming
  ufw default allow outgoing
  ufw allow ssh
  ufw allow 3210/tcp comment "WWA Registry"
  ufw allow 8787/tcp comment "WWA Gateway"
  ufw --force enable
REMOTE

echo ""
echo "==> ✅ WWA stack deployed!"
echo "    Server IP:  $IP"
echo "    Registry:   http://$IP:3210"
echo "    Gateway:    http://$IP:8787"
echo ""
echo "    Configure your agent:"
echo "    export WWA_REGISTRY_URL=http://$IP:3210"
echo "    export IACP_ENDPOINT=$IP:8787"
echo ""
`;

export async function generateHetznerSetup(opts: SetupOptions): Promise<SetupOutput> {
  const scriptPath = `${opts.projectDir}/wwa-hetzner-setup.sh`;
  const content = HETZNER_SCRIPT(opts);

  const { writeFile, mkdir } = await import("fs/promises");
  await mkdir(opts.projectDir, { recursive: true });
  await writeFile(scriptPath, content, "utf-8");
  // make executable (best effort)
  try {
    const { chmod } = await import("fs/promises");
    await chmod(scriptPath, 0o755);
  } catch { /* non-fatal */ }

  return {
    filesWritten: [scriptPath],
    instructions: [
      "WWA Hetzner setup generated!",
      "",
      "Prerequisites:",
      "  1. Hetzner account with SSH key uploaded",
      "  2. HCLOUD_TOKEN env var (read:write API token)",
      "  3. hcloud CLI: https://github.com/hetznercloud/cli",
      "",
      "To deploy:",
      `  chmod +x ${scriptPath}`,
      `  HCLOUD_TOKEN=your_token ${scriptPath}`,
      "",
      "What it does:",
      "  - Creates CX23 VPS in Nuremberg (nbg1)",
      "  - Installs Docker + Docker Compose",
      "  - Deploys WWA Registry (port 3210)",
      "  - Deploys WWA Gateway (port 8787)",
      "  - Configures UFW firewall",
      "  - Prints connection details",
    ].join("\n"),
  };
}
